name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - aensley
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please provide a brief and clear description of the bug.
    validations:
      required: true
  - type: dropdown
    id: client
    attributes:
      label: Client
      description: What type of client is consuming the API?
      options:
        - C#
        - curl
        - Go
        - Java
        - JavaScript (browser)
        - Node.js
        - PHP
        - PowerShell
        - Python
        - Ruby
        - Swift
        - Other
    validations:
      required: true
  - type: dropdown
    id: api
    attributes:
      label: API Endpoint
      description: Which API endpoint has a bug?
      options:
        - /day
    validations:
      required: true
  - type: textarea
    id: parameters
    attributes:
      label: Request Parameters
      description: List the parameters you provided to the request
      value: |
        1. date: value
        2. timestap: value
        3. ...
    validations:
      required: true
  - type: textarea
    id: received-response
    attributes:
      label: Response received
      description: Please copy and paste the entire response received from the API when the bug occurred.
      render: JSON
  - type: textarea
    id: expected-response
    attributes:
      label: What was the expected result?
      description: Please provide an example of the expected result.
      render: JSON
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow the [Code of Conduct](https://github.com/aensley/liturgy-day/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
