name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - aensley
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: api
    attributes:
      label: API Endpoint
      description: Which API endpoint has a bug?
      options:
        - /day
    validations:
      required: true
  - type: dropdown
    id: client
    attributes:
      label: Client
      description: What type of client is consuming the API?
      options:
        - Android
        - Bash / Batch / PowerShell (script)
        - C#
        - Go
        - iOS
        - Java
        - JavaScript
        - Kotlin
        - Node.js
        - PHP
        - Python
        - Ruby
        - Typescript
        - curl / other
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Provide a clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: What was the expected result?
      placeholder: Provide an example of the expected result.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the bug
      placeholder: Provide the steps to reproduce the bug
      value: |
        1. Step 1
        2. Step 2
        3. ...
    validations:
      required: true
  - type: textarea
    id: example-response
    attributes:
      label: Reponse received with the bug
      description: Please copy and paste the entire response received from the API
      render: shell-script
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
