name: integration-test

on:
  check_run:
    types:
      - completed

jobs:
  test:
    if: github.event.check_run.app.slug == 'cloudflare-pages'
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          description: Running integration tests
          sha: ${{ github.event.check_run.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.check_run.head_sha }}

      - name: Set API_HOST
        uses: actions-ecosystem/action-regex-match@v2
        id: api-host
        with:
          text: ${{ github.event.check_run.details_url }}
          regex: 'liturgy-day\/([a-f0-9]+)-'

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run integration-test
        env:
          API_HOST: ${{ steps.api-host.outputs.group1 }}.liturgy-day.pages.dev

      - name: Report prod deployments
        run: |
          branchName="$(gh api -H 'Accept: application/vnd.github+json' \
            /repos/aensley/liturgy-day/check-suites/${{ github.event.check_run.check_suite.id }} \
            --jq '.head_branch')"

          if [ "$branchName" = "main" ]; then
            releaseVersion="${{ github.event.check_run.head_sha }}"
            curl -u ${ASSERTIBLE_DEPLOY_TOKEN}: "https://assertible.com/deployments" -d'{
                "service": "${ASSERTIBLE_SERVICE_ID}",
                "environment": "production",
                "version": "${releaseVersion:0:7}"
            }'
          fi

        env:
          ASSERTIBLE_DEPLOY_TOKEN: ${{ secrets.ASSERTIBLE_DEPLOY_TOKEN }}
          ASSERTIBLE_SERVICE_ID: ${{ secrets.ASSERTIBLE_SERVICE_ID }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          description: Integration test ${{ job.status }}
          sha: ${{ github.event.check_run.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
