name: openapi-diff-pr

on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  openapi-diff-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out HEAD revision
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          path: head
      - name: Check out BASE revision
        uses: actions/checkout@v6
        with:
          ref: ${{ github.base_ref }}
          path: base
      - name: Check for breaking API changes
        uses: oasdiff/oasdiff-action/breaking@6147a58e5d1249a12f42fc864ab791d571a30015 # v0.0.47
        with:
          base: base/src/openapi.yml
          revision: head/src/openapi.yml
          fail-on: ERR
      - name: Generate diff report
        if: always()
        uses: oasdiff/oasdiff-action/changelog@6147a58e5d1249a12f42fc864ab791d571a30015 # v0.0.47
        with:
          base: base/src/openapi.yml
          revision: head/src/openapi.yml
          format: markdown
          output-to-file: ./openapi.md
      - name: Post diff report to PR
        if: always()
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: ./openapi.md
