name: openapi-diff-pr

on: pull_request

jobs:
  openapi-diff-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out HEAD revision
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          path: head
      - name: Check out BASE revision
        uses: actions/checkout@v6
        with:
          ref: ${{ github.base_ref }}
          path: base
      - name: Check for breaking API changes
        uses: oasdiff/oasdiff-action/breaking@v0.0.47
        with:
          base: base/src/openapi.yml
          revision: head/src/openapi.yml
          fail-on: ERR
      - name: Create output directory
        if: always()
        run: mkdir -p ./output
      - name: Generate diff report
        if: always()
        uses: oasdiff/oasdiff-action/changelog@v0.0.47
        with:
          base: base/src/openapi.yml
          revision: head/src/openapi.yml
          format: html
          output-to-file: ./output/openapi.html
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: diff-reports
          path: ./output
